---
name: "Test"

on:
  workflow_call:

env:
  COLORTERM: "yes"
  TERM: "xterm-256color"
  PYTEST_ADDOPTS: "--color=yes"
  CONTAINER_RUNTIME: "docker"

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_tag: "nightly"
            pulp_api_root: "/relocated/djnd/"
            python: "3.11"
          - image_tag: "latest"
            lower_bounds: true
            pulp_https: true
            python: "3.8"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-pip-${{ hashFiles('**/*requirements.txt', '**/*constraints.lock', '**/setup.py', '**/pyproject.toml') }}"
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: "Download wheels"
        uses: "actions/download-artifact@v4"
        with:
          name: "pulp_cli_packages"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python }}"
          allow-prereleases: true
      - name: "Install Python Test Dependencies"
        run: |
          if [ "${{matrix.lower_bounds}}" ]
          then
            pip install dist/pulp_cli_gem-*.whl pulp-glue-gem/dist/pulp_glue_gem-*.whl -r test_requirements.txt -c lower_bounds_constraints.lock
          elif [ "${{matrix.upper_bounds}}" ]
          then
            .ci/scripts/calc_constraints.py pyproject.toml pulp-glue-gem/pyproject.toml  --upper > upper_bounds_constraints.lock
            pip install dist/pulp_cli_gem-*.whl pulp-glue-gem/dist/pulp_glue_gem-*.whl -r test_requirements.txt -c upper_bounds_constraints.lock
          else
            pip install dist/pulp_cli_gem-*.whl pulp-glue-gem/dist/pulp_glue_gem-*.whl -r test_requirements.txt
          fi
      - name: "Run tests"
        env:
          CONTAINER_RUNTIME: "${{ matrix.container_runtime }}"
          IMAGE_TAG: "${{ matrix.image_tag }}"
          FROM_TAG: "${{ matrix.from_tag }}"
          CONTAINER_FILE: "${{ matrix.container_file }}"
          PULP_HTTPS: "${{ matrix.pulp_https }}"
          PULP_OAUTH2: "${{ matrix.pulp_oauth2 }}"
          PULP_API_ROOT: "${{ matrix.pulp_api_root }}"
          OAS_VERSION: "${{ matrix.oas_version }}"
        run: |
          .ci/run_container.sh make test
...
